### PR TITLE
Adds `startEditionFrom` configuration and fixes an error when all weights are 0.

### LINKED ISSUE #620: Changing The Name In Layer Order
Good Morning

Having an issue when I change the layer order name in config js and in the layers folder. I am getting an error message
TypeError: Cannot read properties of undefined (reading 'replace')
    at removeQueryStrings  

unfortunately I have no idea why

### LINKED ISSUE #637: startEditionFrom
Hi Guys

Is there a way to start the count from 1000 or any other number and not 1?

### PR DESCRIPTION
**Pull request by bolshoytoster**
This PR adds a `startEditionFrom` property to `layerConfigurations`. This sets the number the edition starts from, defaulting to `1` if it's not defined. Sol still only starts from `0`.
Resolves #637

This also fixes an error an error that occurs when all weights in a layer are `0`. If they are all `0` now, it just picks a random element.
Should fix #620

### CODE REVIEW

**Comment by bolshoytoster** [comment]
I've also added some commits to improve accessibility (removed some warnings that might confuse people).

**Comment by bolshoytoster** [comment]
## Continuing collection:

- Doesn't delete the `build/` directory

- Now compares the `sha1` hashes to check if DNA exists.

### Reworked `startCreating` to make it more readable/efficient:

- Iterates over `layerConfigurations` and `abstractedIndexes` rather than getting them by index.

- `abstractedIndexes` is calculated per-layer instead of just for the last one.

- Loads existing DNA from `build/json/_metadata.json`.

- Removes one debugLog because it's not relevant anymore.

## Accessibility fixes. Make the tool less confusing/daunting to new users:

- Adds a more concise warning when `src/config.js` has an error.

- Changes `fs.rmdir` to `fs.rm` to gat rid of depracation warning.

- Changes some `throw`s to `console.error`s so it doesn't show the stack trace.

**Comment by ElDla** [comment]
@bolshoytoster I get an error:

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7F80D401F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
 2: 00007FF7F8063146 DSA_meth_get_flags+65542
 3: 00007FF7F8063FFD node::OnFatalError+301
 4: 00007FF7F8995ADE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7F898000D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF7F88235FC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF7F88302A9 v8::internal::Heap::PublishPendingAllocations+1129
 8: 00007FF7F882D27A v8::internal::Heap::PageFlagsAreConsistent+2842
 9: 00007FF7F881FEF9 v8::internal::Heap::CollectGarbage+2137
10: 00007FF7F882879B v8::internal::Heap::GlobalSizeOfObjects+331
11: 00007FF7F886ECCB v8::internal::StackGuard::HandleInterrupts+891
12: 00007FF7F8577486 v8::internal::DateCache::Weekday+8038
13: 00007FF7F8A234B1 v8::internal::SetupIsolateDelegate::SetupHeap+494417
14: 000001B9C1758931

**Comment by bolshoytoster** [comment]
@ElDla bugger, I’ll test it when I get home.

**Comment by bolshoytoster** [comment]
@ElDla I've fixed this, it looks like it works to me.

**Comment by ElDla** [comment]
@bolshoytoster finally managed to test it. The error is gone now and shuffling works. What happens though is after it creates one layer configuration, it skips the numbering for the same number as the number of editions it created just before. For example, if we have three configurations: 20 editions of first configuration (numbers 1-20), 25 editions of second configuration (should be numbers 21-45), and 5 editions of third configuration (should be numbers 46-50). It will create:

- first one is fine, 20 images are created and get numbers 1 to 20;
- second one, 25 editions are created but instead of being names 21 to 45, they get numbers 41-65 (shifted for +20, because the previous config has 20 editions);
- third one, 5 editions are created but are named 91 to 95 (shifted for +25 more, because previous edition has 25 editions)

**Comment by ElDla** [comment]
The shuffling doesn't work anymore. In either case, if shuffling is set to false or true, the number of editions is ok, but the order is wrong (as I described before https://github.com/HashLips/hashlips_art_engine/pull/638#issuecomment-1035324308)

**Comment by bolshoytoster** [comment]
@ElDla if you add `console.log(abstractedIndexes)` just before `if (shuffleLayerConfigurations) {` ~line 404 in `src/config.js` are the numbers in order (not skipping numbers)?

**Comment by ElDla** [comment]
You probably mean line 404 in `src/main.js`? (`config.js` only has 166 lines). I added it and there's no difference.

**Comment by bolshoytoster** [comment]
@ElDla really? It should print a massive array. Have you made sure to save the file?

**Comment by ElDla** [comment]
Yea I did, I actually tried multiple times and saved it every time.

**Comment by bolshoytoster** [comment]
@ElDla I’ve had a check, the layer shuffling doesn’t work. But I can’t seem to replicate what you said about the numbers being offset wrong.

Unrelated, I’ve increased generation speed and memory efficiency by [~30%](https://github.com/HashLips/hashlips_art_engine/issues/881#issuecomment-1060010849) and I’d like to add the changes from #844 to speed it up further.

**Comment by bolshoytoster** [comment]
@ElDla I think I've fixed it in my latest commit.

**Comment by bolshoytoster** [comment]
I've also increased the speed of generation by 4x:
Before:
```sh
$ time node index.js
...
Created edition: 323, with DNA: ...

real	0m32.890s
user	0m32.886s
sys	0m0.124s
```
Now:
```sh
$ time node index.js
...
Created edition: 323, with DNA: ...

real	0m8.366s
user	0m0.441s
sys	0m0.245s
```

As you can see, 32 seconds => 8 seconds = 4x speed increase.

I did this by making all rendering happen in a seperate process, because js threads are stupid. The main performance bottleneck now is due to starting the extra process. If I could get rid of this the generator would run at ungodly speeds.

Unfortunately, it can use quite a lot of memory (each process uses ~ 10 MB * ~30 processes at a time = up to 300MB).

Edit: my latest commit adds a number of optimisations meaning it only uses ~200MB, most of which being node.js overhead.

**Comment by ElDla** [comment]
I tried to test it now and recreate that issue again with the updated code but now another issue appears - the metadata is created, but not the images (folder is empty)

**Comment by bolshoytoster** [comment]
@ElDla the issue I've run into with using a child process is that I haven't been able to get the output from it.

A workaround would be to add `console.log(newDna);` just before `childProcess._handle.spawn({`. Then run the child manually:
```sh
node src/worker.js $(the dna) 1
```

**Comment by ElDla** [comment]
```
the : The term 'the' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if 
a path was included, verify that the path is correct and try again.
At line:1 char:22
+ node src/worker.js $(the dna) 1
+                      ~~~
    + CategoryInfo          : ObjectNotFound: (the:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

B:\Files\NFTs\hashlips_art_engine-main_new\src\worker.js:44
  ctx.drawImage(
      ^

Error: Image given has not completed loading
    at drawElement (B:\Files\NFTs\hashlips_art_engine-main_new\src\worker.js:44:7)
    at B:\Files\NFTs\hashlips_art_engine-main_new\src\worker.js:60:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (B:\Files\NFTs\hashlips_art_engine-main_new\src\worker.js:58:61)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
PS B:\Files\NFTs\hashlips_art_engine-main_new>

```

**Comment by bolshoytoster** [comment]
@ElDla you're meant to put the actual dna there i.e.:
```sh
node src/worker.js 'Background/Black#1.png-Eyeball/White#50.png-Eye color/Yellow#10.png-Iris/Small#60.png-Shine/Shapes#100.png-Bottom lid/High#20.png-Top lid/Middle#50.png' 1
```

**Comment by ElDla** [comment]
I realized that later, silly me :) I think it kind of works (but only one image is created), but do you think there is a more practical way of creating it? Especially when you have 100s of editions.

The most useful version of the code seemed to be the one where everything worked except the numbering was being[ skipped](https://github.com/HashLips/hashlips_art_engine/pull/638#issuecomment-1035324308). But I do know how the code can get messed up (although I'm not at all a programmer) and I really appreciate the work you are doing here!

**Comment by bolshoytoster** [comment]
@ElDla no, that was for debugging. The `src/worker.js` script creates one image according to it's arguments.

If it worked fine doing it manually it should work with `node index.js`.

**Comment by ElDla** [comment]
Ok, I really don't know what I could be doing wrong. I download the code, run `npm install` and `node index.js`, without changing or doing anything else, but the result is metadata files with an empty images folder...

**Comment by ElDla** [comment]
```
Background/Black#1.png-Eyeball/White#50.png-Eye color/Red#1.png-Iris/Large#20.png-Shine/Shapes#100.png-Bottom lid/High#20.png-Top lid/Low#20.png
Created edition: 1, with DNA: 801c6e859f85f99cadba9c2cf0dfc379d8d9077b
Background/Black#1.png-Eyeball/Red#50.png-Eye color/Yellow#10.png-Iris/Medium#20.png-Shine/Shapes#100.png-Bottom lid/High#20.png-Top lid/Middle#50.png        
Created edition: 2, with DNA: 7ca07daa65d81688dc60e2ef67b7c48dc74002dd
Background/Black#1.png-Eyeball/White#50.png-Eye color/Yellow#10.png-Iris/Small#60.png-Shine/Shapes#100.png-Bottom lid/Middle#40.png-Top lid/Middle#50.png     
Created edition: 3, with DNA: 1397ce5d3781bb0eacc7442837fe4de992c5e4b5
Background/Black#1.png-Eyeball/White#50.png-Eye color/Yellow#10.png-Iris/Small#60.png-Shine/Shapes#100.png-Bottom lid/High#20.png-Top lid/Middle#50.png
Created edition: 4, with DNA: a816e74ba5fc0cf87072c485c059e3e39fba454d
Background/Black#1.png-Eyeball/White#50.png-Eye color/Red#1.png-Iris/Medium#20.png-Shine/Shapes#100.png-Bottom lid/Middle#40.png-Top lid/Low#20.png
Created edition: 5, with DNA: 16557a5153cedd460fb4f791046d5bc0bd364151
```
The images folder is still empty though. 

I removed the semicolon in line 344 that was giving me an error.

**Comment by ElDla** [comment]
Any way I try, images aren't there. May I ask, how does it work for you? Are there also only metadata files created or images too?

**Comment by bolshoytoster** [comment]
@ElDla I'm going to revert the change to multiple processes due to this limitation. I'll see if I can do it `async`, otherwise, I might have to add something like jquery as a dependency because it will let me actually clone an object.

**Comment by bolshoytoster** [comment]
@ElDla it is done.

**Comment by ElDla** [comment]
setting `const shuffleLayerConfigurations = true` gives me an error, so I set it to false for now.

I realized today why the numbers are skipped (maybe you noticed before). Original Hashlips code was meant to use `growEditionSizeTo` as following: If I wanted to create 10 editions for each of 3 configurations, I would set it to:

1st configuration - growEditionSizeTo: 10,
2nd configuration - growEditionSizeTo: 20,
1st configuration - growEditionSizeTo: 30,

This would give me 10 of each, altogether 30 images. Similary, using `startEditionFrom` I thought I should put it like this to get same result:

1st configuration - startEditionFrom: 1, growEditionSizeTo: 10,
2nd configuration - startEditionFrom: 11, growEditionSizeTo: 20,
1st configuration - startEditionFrom: 21, growEditionSizeTo: 30,

But then numbers are being skipped. I realized that `startEditionFrom` actually defines how many numbers will be skipped.

I tested it more and I found the only way to make the numbering correct is to set the first one from 1 to 10, and all the next cofigurations 0 to 9. I set first one to 1 to 10 or else the numbering will start at 0, but if I set the next configs the same way, the numbering will be skipped for 1 with each new configuration. So the best way to do it right now is like this:
 
1st configuration - startEditionFrom: 1, growEditionSizeTo: 10,
2nd configuration - startEditionFrom: 0, growEditionSizeTo: 9,
1st configuration - startEditionFrom: 0, growEditionSizeTo: 9,

If I want to create for example three more cofigurations later on, continuing from where i left, I can do this by setting it like this:

4th configuration - startEditionFrom: 31, growEditionSizeTo: 40,
5th configuration - startEditionFrom: 0, growEditionSizeTo: 9,
6th configuration - startEditionFrom: 0, growEditionSizeTo: 9,

**Comment by bolshoytoster** [comment]
@ElDla I think I've fixed both issues.

**Comment by ElDla** [comment]
Shuffling I think it works!

The order though not yet. 

configuration 1: 1 to 10 --> named 1 to 10
configuration 2: 11 to 20 --> named 11-31

Creating a new batch (for example 32-42 and 43 to 53) later is messier now, I'm not sure what happens but numbers are wrong and only one configuration is created.

**Comment by bolshoytoster** [comment]
@ElDla I've changed `growEditionSizeTo` to be the size of the collection, instead of the number to build to. I should probably change the name but I want to keep compatibility with the main repo.

**Comment by ElDla** [comment]
Almost there! the only minor thing now is that the last configuration (whether it is 2nd, 3rd.. doesn't matter) creates one more edition than it is specified with `growEditionSizeTo`

**Comment by bolshoytoster** [comment]
@ElDla I think I've fixed this now.

**Comment by ElDla** [comment]
It all works now! I will let you know if I find any other bug later, but this should be it. Thanks!

**Comment by ElDla** [comment]
Just today I noticed that` options: {displayName: "Name Displayed"} ` is not working. I'm not sure since when because because I didn't check metadata before when testing.

Similarly, `bypassDNA: true` doesn't work properly, but I also am not sure if your fork was created before Hashlips added this into his code.

**Comment by bolshoytoster** [comment]
@ElDla I've  just fixed `displayName`, what does `bypassDNA` do?

**Comment by ElDla** [comment]
`bypassDNA` should make it possible to exclude some of the traits from DNA. Without it, you can get for example two images that are completely same except for the background. From Readme: "If you want to have a layer ignored in the DNA uniqueness check, you can set bypassDNA: true in the options object. This has the effect of making sure the rest of the traits are unique while not considering the Background"

I haven't used it before so I don't know if it was working or not at any point.

**Comment by bolshoytoster** [comment]
@ElDla does it work now?

**Comment by ElDla** [comment]
I think so!

**Pull request merged**
