### PR TITLE
Add a script to refresh Opensea

### PR DESCRIPTION
**Pull request by AndyJiangPro**

### CODE REVIEW

**Comment by AndyJiangPro** [comment]
I chose the wrong merge target. I was supposed to choose the Next-DAO one. sorry for any inconvenience caused.

**Comment by thepeanutgalleryandco** [comment]
@AndyJiangPro if possible, can I perhaps DM you on Discord? Would like to ask your assistance on something if possible?

**Comment by AndyJiangPro** [comment]
sure, LvDou#0950 @thepeanutgalleryandco

**Comment by thepeanutgalleryandco** [comment]
@AndyJiangPro it says I can't add you, can you please add me? ThePeanutGalleryAndCo#9888

**Pull request closed without merging**
