### PR TITLE
Deterministically psuedorandom generation

### PR DESCRIPTION
**Pull request by GalaxysHub**
Purpose:

The same set of images and metadata can be generated pseudorandomly. 

This is useful when sharing large sets of image files with teammates. The same set of images can be regenerated instead of sharing a large folder full of images. It is also useful for generating more images with the same characteristics for the same set of NFTs. For example, profile pictures of a character from a different angle can be created by editing the images and rerunning the script.

The function is modular and doesn't add additional lines of code to the main file. However, the editionCount and failedCount now have to be passed through several functions to generate the background.

Configuration:

Set `deterministicallyRandom = true`  in the config file.
Change the `seed ` value to generate a new set of images

### CODE REVIEW

**Comment by illushane** [comment]
Hi Andrew, Thanks. This is what I am looking for. I am a designer who is creating my own NFT. I'd like to know what "value" I need to put in "seed" to make this work?

**Comment by laygir** [comment]
@HashLips this would have been a nice addition. Do we already have something similar in the codebase that prevents this PR from being merged 👀 
I am looking for a way to produce same set of images at everytime I run the app, this would have solved it 😎

**Comment by BadFriendsMedia** [comment]
Does this work for a set of images generated before upddating the engine with this pull?

**Comment by GalaxysHub** [comment]
@HashLips, is there a reason this PR has not been accepted yet? I'm willing to make any modifications necessary

**Comment by novaknole** [comment]
I might wonder, why not using https://github.com/davidbau/seedrandom package for this ?

**Comment by GalaxysHub** [comment]
> I might wonder, why not using https://github.com/davidbau/seedrandom package for this ?

I wasn't aware of that library but it honestly looks a lot cleaner than what I did

**Comment by GalaxysHub** [comment]
I'm going to close this PR and resubmit it using the seedrandom library

**Pull request closed without merging**
